package com.mibs.cabinet.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;


import com.mibs.cabinet.DicomHandler;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
    	DicomHandler classUnderTest = new DicomHandler( null );
        assertNotNull("test message", classUnderTest.getGreeting());
    }
}
